name: Build and Push Docker Image

on:
  push:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest

      - name: Trigger Coolify Deployment
        run: |
          curl --request GET \
            --url 'https://coolify.uispace.co/api/v1/deploy?uuid=pg4g48wwwck8ck8koc0gs84o&force=false' \
            --header 'authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
        env:
          COOLIFY_TOKEN: ${{ secrets.COOLIFY_TOKEN }}
