name: Deploy to Coolify
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy to Coolify
    runs-on: ubuntu-20.04
    steps:
      - uses: manicmade/coolify-actions@v0.0.1
        with:
          coolify-url: ${{ secrets.COOLIFY_URL }}
          coolify-app-id: ${{ secrets.COOLIFY_APP_ID }}
          coolify-token: ${{ secrets.COOLIFY_TOKEN }}
