name: Build Static Image
on:
  push:
    branches: ["develop"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: themarkwill/coolify-actions@v0.0.3 #deploy
        with:
          coolify-url: ${{ secrets.COOLIFY_URL }} # Required
          coolify-app-id: ${{ secrets.COOLIFY_APP_ID }} #Required
          coolify-token: ${{ secrets.COOLIFY_TOKEN }} #Required
